NO_GPU: 1                 # 1: run on CPU, 0: run on GPUs
DUMP_LOCATION: datadump   # path to dump models and log
EXP_NAME: habitat_objnav_2022
# datasets: habitat_objnav_2022, habitat_objnav_2023, goat
DATASET: habitat_objnav_2022
VISUALIZE: 0              # 1: render observation and predicted semantic map, 0: no visualization
PRINT_IMAGES: 1           # 1: save visualization as images, 0: no image saving
GROUND_TRUTH_SEMANTICS: 1 # 1: use ground-truth semantics (for debugging / ablations)
seed: 1
SHOW_RL_OBS: False         # whether to show the observations passed to RL policices, for debugging

ENVIRONMENT:
  max_num_sub_task_episodes: 10

AGENT:
  max_steps: 500          # maximum number of steps before stopping an episode
  panorama_start: 1       # 1: turn around 360 degrees when starting an episode, 0: don't
  exploration_strategy: frontier
  frontier_metric: distance  # metric to use for frontier selection ("distance", "semantics")
  exploration_type: raycast
  radius: 0.05            # robot radius (in meters)

  SEMANTIC_MAP:
    semantic_categories: dataset # map semantic channel categories ("coco_indoor", "longtail_indoor", "mukul_indoor")
    # num_sem_categories: 380           # number of map semantic channel categories (16, 257, 35)
    map_size_cm: 4800        # global map size (in centimeters)
    map_resolution: 5        # size of map bins (in centimeters)
    vision_range: 100        # diameter of local map region visible by the agent (in cells)
    global_downscaling: 2    # ratio of global over local map
    du_scale: 4              # frame downscaling before projecting to point cloud
    cat_pred_threshold: 5.0  # number of depth points to be in bin to classify it as a certain semantic category
    exp_pred_threshold: 1.0  # number of depth points to be in bin to consider it as explored
    map_pred_threshold: 1.0  # number of depth points to be in bin to consider it as obstacle
    explored_radius: 150     # radius (in centimeters) of visually explored region
    been_close_to_radius: 200  # radius (in centimeters) of been close to region
    target_blacklisting_radius: 100 # radius (in centimeters) of region around goal to blacklist if object isn't a valid target
    must_explore_close: False
    min_obs_height_cm: 10    # minimum height (in centimeters) of obstacle to be considered as obstacle
    goal_filtering: True      # If True, gets the largest connected component of the goal map
    record_instance_ids: True # whether to predict and store instance ids in the map

  PLANNER:
    collision_threshold: 0.10       # forward move distance under which we consider there's a collision (in meters)
    min_obs_dilation_selem_radius: 1    # radius (in cells) of obstacle dilation structuring element
    obs_dilation_selem_radius: 3    # radius (in cells) of obstacle dilation structuring element
    map_downsample_factor: 1            # optional downsampling of traversible and goal map before fmm distance call (1 for no downsampling, 2 for halving resolution)
    map_update_frequency: 1             # compute fmm distance map every n steps 
    step_size: 5                    # maximum distance of the short-term goal selected by the planner
    discrete_actions: True         # discrete motion planner output space or not
    min_goal_distance_cm: 25

  SUPERGLUE:
    max_keypoints: 1024
    keypoint_threshold: 0.005
    nms_radius: 4
    superglue_model: indoor           # or outdoor
    sinkhorn_iterations: 20
    match_threshold: 0.2
    score_function: confidence_sum    # or match_count
    score_thresh_image: 24.5  # real-world experiments used 6.0
    score_thresh_lang: 0.24
    match_projection_threshold: 0.2   # confidence must be at least this high to project as goal point.
    goto_past_pose: True

  DETIC:
    config_file: Detic/configs/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml
    vocabulary: custom
    custom_vocabulary: chair,sofa,bed,toilet,potted_plant,tv_monitor
    confidence_threshold: 0.2
    weights: Detic/models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth
    augment_mask_with_box: True